$(function() {
    var availableTags = [
        "AGR+047 Séance de rééducation des fonctions neuromusculaires pour affection neurologique centrale dégénérative",
        "AGR+102 Séance de rééducation des fonctions neuromusculaires pour affection neurologique centrale en phase de récupération",
        "AGR+298 Séance de rééducation des fonctions neuromusculaires pour affection neurologique centrale en phase précoce",
        "ALM+220 Séance de développement d'une capacité senstive et/ou motrice du membre supérieur par réalisation de plusieurs tâches élémentaires combinées et coordonnées",
        "ANM+093 Séance de restauration ou éducation analytique d'une fonction sensitive et/ou motrice du membre supérieur par réalisation d'une tâche élémentaire",
        "ANQ+149 Evaluation iniale des fonctions sensitives et/ou motrices des membres supérieurs sans batterie de test",
        "ANQ+171 234 218 cf idem avec batterie de test",
        "ANQ+174 Evaluation finale des fonctions sensitives et/ou motrices des membres supérieurs sans batterie de test",
        "ANQ+208 Evaluation intermédiaire des fonctions sensitives et/ou motrices des membres supérieurs sans batterie de test",
        "ANR+036 antalgique après thoracotomie ou chirrurgie abdominale (massage et/ou agents physiques)",
        "APR+014 Séance de rééducation des fonctions neuromusculaires pour affection neurologique périphérique dégénérative",
        "APR+036 Séance de rééducation des fonctions neuromusculaires pour affection neurologique périphérique en phase précoce",
        "APR+187 Séance de rééducation des fonctions neuromusculaires pour affection neurologique périphérique en phase de récupération",
        "AZQ+131 Evaluation initiale pour rééducation des fonctions neuro-musculaires",
        "AZQ+144 Evaluation intermédiaire pour rééducation des fonctions neuro-musculaires",
        "AZQ+164 Evaluation finale pour rééducation des fonctions neuro-musculaires",
        "AZR+199 Séance de rééducation des fonctions neuromusculaires pour mouvements anormaux",
        "CER+030 Séance de rééducation des troubles vestibulaires",
        "CER+223 Séance de rééducation des fonctions de l'équilibre",
        "CER+223 Séance de rééducation des troubles de l'équilibre",
        "DKQ+008 Quantification des capacités fonctionnelles cardiovasculaires et/ou respiratoires pour la réalisation des gestes quotidiens",
        "DKR+195 Séance individuelle de réentrainement à l'effort aèrobie sans ergomètre",
        "DKR+200 Séance collective vélo",
        "EQR+175 test de marche de 6 minutes LHQ+048 Evaluation initiale pour rééducation des fonctions de la colonne vertébrale",
        "EQR+175 épreuve de marche de 6 minutes ( test de marche de 6 minutes )",
        "EQR+275 épreuve de montée d'escalier ( test de montée d'escalier )",
        "FCJ+089 Séance de drainage lymphatique par massage d'un membre",
        "FCJ+164 Séance de drainage lymphatique par pressothérapie d'un membre",
        "GLJ+050 Séance de désencombrement instrumental des bronches",
        "GLJ+199 Séance de désencombrement non instrumentale d'un patient avec exacerbation des symptômes",
        "GLJ+255 Séance de désencombrement non instrumentale d'un patient stable",
        "GLR+074 Séance individuelle d'entrainement des muscles inspiratoires avec dispositif résistif",
        "GLR+077 Séance individuelle de gymnastique pour réadaptation respiratoire",
        "GLR+093 Séance de rééducation respiratoire préparatoire à un acte de chirurgie thoracique ou abdominal",
        "GLR+131 Séance individuelle d'entrainement des muscles expiratoires et/ou phonatoires",
        "GLR+167 Ventilation dirigée abdomino-diaphragmatique et d'entrainement des muscles inspiratoires avec dispositif résistif",
        "GLR+169 Séance collective d'entrainement des muscles expiratoires et/ou phonatoires",
        "GLR+170 Séance de rééducation respiratoire aprés chirurgie thoracique ou abdominal",
        "GLR+186 Séance de rééducation respiratoire pour séquelles d'épanchement pleurale",
        "GLR+206 Rééducation respiratoire par méthode instrumentale (spirométrie incitative)",
        "GLR+224 Séance de rééducation respiratoire pour épanchement pleurale",
        "GLR+226 Séance de ventilation dirigée abdomino-diaphragmatique",
        "GLR+285 Séance individuelle de réadaptation respiratoire par entrainement des membres supérieurs",
        "GLR+290 Séance collective d'entrainement des muscles inspiratoires avec dispositif résistif",
        "LHQ+063 Evaluation intermédiaire pour rééducation des fonctions de la colonne vertébrale",
        "LHQ+344 Evaluation finale pour rééducation des fonctions de la colonne vertébrale",
        "MKQ+001 Evaluation initiale pour rééducation des fonctions du membre supérieur",
        "MKQ+152 Evaluation intermédiaire pour rééducation des fonctions du membre supérieur",
        "MKQ+222 Evaluation finale pour rééducation des fonctions du membre inférieur",
        "MKQ+272 Evaluation finale pour rééducation des fonctions du membre supérieur",
        "MKQ+284 Evaluation initiale pour rééducation des fonctions du membre inférieur",
        "MKQ+295 Evaluation intermédiaire pour rééducation des fonctions du membre inférieur",
        "MKR+023 Séance de rééducation des fonctions du membre supérieur pour lésions ostéoarticulaires dégénératives",
        "MKR+126 Séance de rééducation des fonctions du membre supérieur pour lésion traumatique",
        "MKR+248 Séance de rééducation des fonctions du membre supérieur après réparation de lésion traumatique ou correction de vice architecturale",
        "MKR+287 Séance de rééducation des fonctions du membre supérieur après correction de lésions ostéoarticulaires",
        "NKQ+021 evaluation de la marche sur terrain plat NKQ+069 evaluation de la marche sur parcours amenagé avec obstacles",
        "NKR+010 Séance individuelle de rééducation ou de réadaptation à la marche",
        "NKR+059 Séance collective de réadaptation à la marche",
        "NKR+130 Séance de rééducation des fonctions du membre inférieur après correction de lésions ostéoarticulaires",
        "NKR+174 Séance individuelle de réadaptation à la marche en parcours aménagé avec obstacles",
        "NKR+177 Séance de rééducation des fonctions du membre inférieur pour lésion traumatique",
        "NKR+204 Séance de rééducation des fonctions du membre inférieur après réparation de lésion traumatique ou correction de vice architecturale",
        "NKR+280 Séance de rééducation des fonctions du membre inférieur pour lésions ostéoarticulaires dégénératives",
        "PBR+256 Séance individuelle de mobilisation articulaire",
        "PCM+064 Séance individuelle de renforcement musculaire contre résistance avec matériel training musculaire individuel",
        "PCM+283 Séance individuelle de renforcement musculaire contre résistance sans matériel",
        "PCQ+057 quantification de la force et de l'endurance musculaire périphérique sans appareil",
        "PCQ+140 Bilan de la force musculaire périphérique ",
        "PCQ+199 quantification de la force et de l'endurance musculaire périphérique avec appareils ",
        "PCR+285 Séance de réadaptation à l'effort musculaire après rééducation de l'appareil locomoteur",
        "PEE+041 Séance de verticalisation sans appareil dynamique",
        "PEE+175 Séance de verticalisation avec appareil dynamique",
        "PER+096 Séance d'apprentissage aux transferts",
        "PER+103 Séance d'apprentissage de l'utilisation d'un fauteuil roulant en établissement",
        "PER+154 Séance collective de prévention des chutes",
        "PER+163 Séance d'apprentissage de l'optimisation énergique des gestes quotidiens",
        "PER+223 Séance de rééducation des troubles de la posture axiale",
        "PER+250 Séance individuelle de prévention des chutes",
        "PER+250 Séance individuelle de rééducation de prévention des chutes",
        "PER+253 Séance d'apprentissage aux transferts en situation d'activité physique et/ou sportive",
        "PER+253 Séance individuelle d'apprentissage des transferts en situation d'activité physique et/ou sportive",
        "PER+285 Séance collective de gymnastique",
        "PZE+057 Séance de massage",
        "PZL+208 Séance d'application d'agent physique à visée thérapeutique U.S éléctrothérapie excito-moteur installation réglages des paramètres",
        "PZL+212 Mise en place d'un dispositif générateur d'agent physique à visée thérapeutique I.R éléctrothérapie",
        "ZZR+079 Séance individuelle d'information du patient et/ou de son entourage",
    ];
    $("#tags").autocomplete({
        source: availableTags
    });
});


